### PR TITLE
Print timezone in time stamp

### PR DESCRIPTION
**Pull request by hasit**
- Get local timezone of the user
- Print timezone along with current time stamp information

### CODE REVIEW

**Comment by hasit** [comment]
At the group meeting with @davidsocha, we discussed that researchers using Transana might not be in the same timezone. Hence, adding timezone information to the timestamp feature of NoteEditor module would be helpful.

I wasn't sure as to which branch I should be sending the PR to. It would be very helpful to have some sort of installation/build guide in the repo as well. I look forward to reading your comments on this.

**Comment by davidsocha** [comment]
The new code is not fully localized. For instance, the Europeans (and others) use DD/MM/YYYY, not MM/DD/YYYY.  Yet the new code eliminates the comment to localize the date time. Would it be better to use a format that is unambiguous (or at least to keep the TODO comment in the code)? FYI, I hope to be using Transana collaboratively with Europeans within the year.

David

**Comment by DKWoods** [comment]
Hi Hasit, and welcome to Transana's git repository.

I see the need this change is designed to address, but I have one concern.

https://docs.python.org/2/library/time.html has a footnote at the bottom that states:

The use of %Z is now deprecated, but the %z escape that expands to the preferred hour/minute offset is not supported by all ANSI C libraries.

Can you do a quick check of Python 3.4 / 3.5 to see if this parameter is still supported?

The installation/build guide, such as it is, is on the main Transana web site.

**Comment by DKWoods** [comment]
Hi Hasit,

I've created a new branch called timezone.  Please commit your changes to that branch rather than the master branch.  That way, I can explore and test your changes before integrating them into Transana's main code base.

Thanks, David

**Comment by DKWoods** [comment]
Hi David,

It's tough to localize the time stamps in the Notes.  They're just text once they are inserted.  If we were to localize that text representation, then in an international team, you'd have time stamps in different forms depending on the localization of the person who inserted the time stamp.  I would imagine people would find that even more confusing.  That's one of the reasons I've never taken care of that TODO: item.

David

**Comment by hasit** [comment]
Hello @DKWoods,

As of Python 3.5.1, %z is supported in the built-in time library (https://docs.python.org/3/library/time.html#time.strftime). So I do not think that that would be a problem.

Thank you.

**Comment by hasit** [comment]
Hello @davidsocha,

I am aware that Europeans and others use DD/MM/YYYY date format. I have used that all my life as well. 

This PR adds timezone information (-0800 for us). One more issue with adding localization support is DST.

I understand the need to dynamic localization. From what I understand, and what @DKWoods mentioned, the timestamp is a static string. This means that the NoteEditor module would need to parse the notes every time upon opening, check the local timezone of the user and print the right date format. This calls for major refactoring and redesigning and could be part of a future release.

**Comment by DKWoods** [comment]
Interesting.  Notice that %Z is the same but %z is different, showing 
the offset rather than the time zone name.  That's not necessarily a 
problem, but I anticipate that Transana will move to Python 3.x at some 
point when wxPython / Phoenix can fully support it.  Please plan 
accordingly.

David

**Comment by davidsocha** [comment]
How about using the unambiguous format DD MMM YYYY (e.g., 24 May 2016)?

David

**Comment by hasit** [comment]
@DKWoods, would you be able to push your timezone branch upstream? Since Github doesn't allow PR host branch to be changed, I will close this PR and send in a new one with the changes suggested by @davidsocha. I will also reference this PR in the new one for future reference.

**Comment by DKWoods** [comment]
Hi Hasit,

Sorry for the delay.  I've now pushed the timezone branch so you can get 
to it.

David

**Comment by DKWoods** [comment]
@davidsocha - Being an American, I prefer the MMM DD, YYYY form.

**Comment by davidsocha** [comment]
Either one works for me. As long as it is unambiguous.

David

On May 25, 2016, at 2:33 PM, David Woods <notifications@github.com<mailto:notifications@github.com>> wrote:


@davidsocha<https://github.com/davidsocha> - Being an American, I prefer the MMM DD, YYYY form.

-

**Comment by hasit** [comment]
Closed this PR and sent a new one #19

**Comment by davidsocha** [comment]
So, if I am collaborating with researchers in US, Canada, and Norway, and we are all making notes into the same document, there will be several differently formatted versions of the date-time strings depending upon who created which strings. Is this going to be a problem?  Does Transana ever need to convert the strings in such files back into the computer representation of a date-time? If so, is that going to work if the set of date-time strings in a file come from multiple different time locales?

**Pull request closed without merging**
